### ISSUE TITLE
Problem with using context.log method

### ISSUE THREAD

**Issue by andrzejsliwa** [eawsy/aws-lambda-go-shim#49] opened 2017-12-09 18:46 UTC
Like I described below there is issue with using `context.log` method:

https://github.com/serverless/serverless/issues/4544

Which is resulting with problem on local invocation.
Situation is not clear with used method here:
https://github.com/eawsy/aws-lambda-go-shim/blob/a9e5c8b1c1f09a38d3706e552c87ad945299f1f4/src/proxy.py#L45

is not documented in official documentation:
http://docs.aws.amazon.com/lambda/latest/dg/python-context-object.html#python-context-object-methods

hoverer exist on AWS stack:
https://gist.github.com/gene1wood/c0d37dfcb598fc133a8c

I see two options:

- add it to fake context: https://github.com/serverless/serverless/issues/4544 (however its not officially documented)
- replace it in proxy, (with logger or other print method):
```python
import json
import os
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

import runtime

def dump(obj):
    if hasattr(obj, '__slots__'):
        return {slot: getattr(obj, slot) for slot in obj.__slots__}
    return obj.__dict__

class Proxy(object):
    def __getattr__(self, name):
        if name == "init":
            return lambda: None
        runtime.lookup(name)
        return self._handle

    def _handle(self, evt, ctx):
        return json.loads(runtime.handle(
            json.dumps(evt),
            json.dumps(ctx, default=dump),
            json.dumps({k: v for k, v in ((k, os.getenv(k)) for k in (
                "AWS_ACCESS_KEY_ID",
                "AWS_SECRET_ACCESS_KEY",
                "AWS_SESSION_TOKEN",
                "AWS_SECURITY_TOKEN",
                "_X_AMZN_TRACE_ID",
            )) if v}),
            logger.info, ctx.get_remaining_time_in_millis))
```

I'm looking forward to discuss about it

**Comment by fsenart** [comment] 2017-12-13 08:28
Hi @andrzejsliwa,

At the beginning, `context.log` was here and as we have to provide a seamless integration for the shim, this method is also present in the shim.
Local stub/mock environments should reproduce as precisely as possible the AWS Lambda runtime. So they have to provide at least a stub `context.log`. I agree that it's no more present in the official doc but as it was here from the beginning, people may depend on it. And that's also the reason it's still present in the official runtime (but without any advertising maybe because it will be removed in future versions of the runtime).
My general position: if official runtime has it, we have to have it too and TBH the AWS documentation is far from being exact and exhaustive :smile:

**Comment by fsenart** [comment] 2018-01-17 17:41
Close the issue, as the official runtime is out 🎉

**Closed by fsenart** 2018-01-17 17:41 UTC
