### ISSUE TITLE
SSL certificates cannot be loaded

### ISSUE THREAD

**Issue by bfreis** [eawsy/aws-lambda-go-shim#1] opened 2017-01-09 21:11 UTC
Hi!

For some reason, when using this new version my code fails to make any HTTPS connections. I investigated and noticed that `x509.SystemCertPool()` returns a pool with no certificates. I checked that the CA certificate files are indeed there in the Lambda environment, but it fails. I then tried to copy-and-paste the x509/example_test.go test functions, specifically ExampleCertificate_Verify() and ExampleParsePKIXPublicKey() https://golang.org/src/crypto/x509/example_test.go?m=text and it fails when parsing the certificate files.

I also tried to go-bindata a PEM file with certificates that I can for sure parse on my local machine and then try to have x509.SystemCertPool() add that, but I get the same certificate parsing issue.

It's very strange: parsing certificates fail in the Lambda environment, but it works on my machine.

With the previous version (ie, eawsy/aws-lambda-go), it works fine! The exact same code, with the exact same certificate data and tests, works fine on that previous version.

Have you seen this? Any ideas what could be causing it?

Thanks!
Bruno

**Comment by bfreis** [comment] 2017-01-09 21:15
Here's the error when it tries to parse an SSL cert:

failed to parse certificate from server: asn1: structure error: tags don't match (4 vs {class:0 tag:16 length:1227 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}

**Comment by bfreis** [comment] 2017-01-09 21:18
Oh, I also tried invoking my code directly (ie, I added a go build instruction on the example Makefile to generate a binary) inside a Docker container using the -shim image, it was successful. I also tried to run the code using the same binary inside the original amazonlinux docker image and it was also successful.

Maybe it's some mysterious issue related to the plugin mechanism?

**Comment by fsenart** [comment] 2017-01-09 22:43
Hi @bfreis. We heard about this problem a few days ago in the gitter channel. After investigation, it seems to be related to golang plugins. We've informed the golang team golang/go#18584.

**Comment by fsenart** [comment] 2017-01-10 00:01
As this bug is related to the handler's dynamic signature feature, I will disable the feature for now so that the shim works. I will enable it once the issue is fixed.

**Comment by fsenart** [comment] 2017-01-10 23:55
@bfreis can you please test with the updated docker image `docker pull eawsy/aws-lambda-go-shim:latest`. As far as I've tested, the issue seems resolved with the release of go 1.8rc1 golang/go@3de6e96.
Please keep me informed asap.

**Comment by bfreis** [comment] 2017-01-11 07:18
I'm now getting a different error message when I invoke the lambda:

> Unable to import module 'handler': plugin.Open: plugin was built with a different version of package github.com/eawsy/aws-lambda-go-core/service/lambda/runtime

**Closed** 2017-01-11 16:55 UTC
